name: PR Checks
on:
    pull_request:
        branches:
            - 'main'

jobs:
    pr-checks:
        uses: ./.github/workflows/build-and-deploy.yml
        permissions:
            contents: read
        with:
            env: dev
            appOrigin: 'https://www.ansatt.dev.nav.no'
            editorialFrontpageOrigin: 'https://www.ansatt.dev.nav.no/tilbakemelding'
            skipDeploy: true
        secrets:
            READER_TOKEN: ${{ secrets.READER_TOKEN }}
